// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9X5Ybl49d0V3Iriyz4PcSt4zdZ9ch5zs',
    appId: '1:2609380409:web:5904aa2471a6123c8021e8',
    messagingSenderId: '2609380409',
    projectId: 'thingstodo-be973',
    authDomain: 'thingstodo-be973.firebaseapp.com',
    storageBucket: 'thingstodo-be973.appspot.com',
    measurementId: 'G-YKQVVTW2Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoHGwq6aRq1zJOTVa-ohSLGFljZtuoh5g',
    appId: '1:2609380409:android:7cccd77cdbda3b848021e8',
    messagingSenderId: '2609380409',
    projectId: 'thingstodo-be973',
    storageBucket: 'thingstodo-be973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeFOec59XIvl05l-3HqFit5EmDjYszidY',
    appId: '1:2609380409:ios:aa071a551260eaca8021e8',
    messagingSenderId: '2609380409',
    projectId: 'thingstodo-be973',
    storageBucket: 'thingstodo-be973.appspot.com',
    iosClientId: '2609380409-msdcqqjej3086i2gps7ckcrfvftlp9bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingsToDo',
  );
}
